import {
    AGENT_COMMUNICATION_PEER_STATUS,
    AGENT_ROLE,
    BaseAgentCommunicationChannel,
    type AgentCommunicationMessage,
    type AgentCommunicationMessageHandler,
    AgentCommunicationMessageFactory,
    type AgentCommunicationPeer,
    type AgentCommunicationPeerStatusHandler,
    type GridFormationAcceptanceMessage,
    type GridFormationProposalMessage,
    type GridFormationReleaseAcknowledgementMessage,
    type GridFormationReleaseMessage,
    PEER_MESSAGE_TYPE,
    type RendezvousArrivedMessage,
    type RendezvousArrivalAcknowledgementMessage,
    type RendezvousAssignmentMessage,
} from "../../../communication/index.js";
import { SCORE_EFFECT_LIFETIME } from "../../../_score-effect-lifetime.js";
import { CellScoreEffect } from "../../../utils/_cell-score-effects.js";
import { Position } from "../../../utils/position.js";
import { GridPositionObjective } from "./_position-objective.js";

/** State of one local participant in the rendezvous protocol. */
export enum RENDEZVOUS_COORDINATION_STATE {
    CONSIDERING = "considering",
    PROPOSING = "proposing",
    COMMITTED = "committed",
    WAITING_FOR_PEER = "waiting-for-peer",
    WAITING_FOR_RELEASE = "waiting-for-release",
    COMPLETED = "completed",
}

/** Transport-neutral rendezvous generated by the LLM mission planner. */
export interface RendezvousCoordinationPlan {
    readonly rendezvousId: string;
    readonly reward: number;
    readonly llmAgentTarget: Position;
    readonly bdiAgentTarget: Position;
}

/** Grid formation whose peer target is selected by the peer itself. */
export interface GridFormationCoordinationPlan {
    readonly rendezvousId: string;
    readonly reward: number;
    readonly llmAgentObjective: GridPositionObjective;
    readonly bdiAgentObjective: GridPositionObjective;
}

/** Resolves a received predicate using the accepting agent's current world. */
export type GridPositionResolutionHandler = (
    objective: GridPositionObjective,
    currentPosition: Position,
    excludedPositions: readonly Position[],
) => Position | undefined;

/** Read-only coordinator state useful to tests and observers. */
export interface RendezvousCoordinationSnapshot {
    readonly rendezvousId: string;
    readonly localTarget: Position | undefined;
    readonly peerTarget: Position | undefined;
    readonly reward: number;
    readonly state: RENDEZVOUS_COORDINATION_STATE;
    readonly peerArrived: boolean;
    readonly arrivalAcknowledged: boolean;
}

interface RendezvousRecord {
    readonly rendezvousId: string;
    readonly reward: number;
    localTarget: Position | undefined;
    peerTarget: Position | undefined;
    readonly localObjective: GridPositionObjective | undefined;
    readonly assignmentMessage: RendezvousAssignmentMessage | undefined;
    formationProposalMessage:
        GridFormationProposalMessage | undefined;
    readonly peerObjective: GridPositionObjective | undefined;
    readonly receivedFormationProposalMessage:
        GridFormationProposalMessage | undefined;
    formationAcceptanceMessage:
        GridFormationAcceptanceMessage | undefined;
    readonly requiresExternalRelease: boolean;
    state: RENDEZVOUS_COORDINATION_STATE;
    peerArrived: boolean;
    arrivalAcknowledged: boolean;
    arrivalMessage: RendezvousArrivedMessage | undefined;
    releaseMessage: GridFormationReleaseMessage | undefined;
    commitmentWaiters: Set<() => void>;
    completionWaiters: Set<() => void>;
}

export type RendezvousStateChangeHandler = () => void;

/** Contract connecting rendezvous communication to an autonomous planner. */
export abstract class BaseRendezvousCoordinator {
    abstract start(): void;
    abstract stop(): void;
    abstract propose(plan: RendezvousCoordinationPlan): void;
    abstract considerGridFormation(plan: GridFormationCoordinationPlan): void;
    abstract commitSelectedGridFormation(
        effectId: string,
        target: Position,
    ): boolean;
    abstract isGridFormationEffect(effectId: string): boolean;
    abstract waitForGridFormationCommit(): Promise<void>;
    abstract observePosition(position: Position): void;
    abstract activeScoreEffects(): readonly CellScoreEffect[];
    abstract isWaitingForPeer(): boolean;
    abstract waitForPeer(): Promise<void>;
    abstract releaseWaitingGridFormations(): boolean;
    abstract consumeCompletedRendezvousIds(): readonly string[];
    abstract snapshots(): readonly RendezvousCoordinationSnapshot[];
    abstract subscribeStateChanges(handler: RendezvousStateChangeHandler): void;
}

/** Reliable two-peer rendezvous state machine over the shared agent channel. */
export class PeerRendezvousCoordinator extends BaseRendezvousCoordinator {
    private readonly records: Map<string, RendezvousRecord> =
        new Map<string, RendezvousRecord>();
    private readonly stateChangeHandlers: Set<RendezvousStateChangeHandler> =
        new Set<RendezvousStateChangeHandler>();
    private readonly completedRendezvousIds: string[] = [];
    private readonly messageHandler: AgentCommunicationMessageHandler;
    private readonly peerStatusHandler: AgentCommunicationPeerStatusHandler;
    private retryTimer: NodeJS.Timeout | undefined;
    private started: boolean = false;
    private latestPosition: Position | undefined;

    constructor(
        private readonly channel: BaseAgentCommunicationChannel,
        private readonly localRole: AGENT_ROLE,
        private readonly retryMilliseconds: number = 1_000,
        private readonly resolveGridPosition:
            GridPositionResolutionHandler | undefined = undefined,
    ) {
        super();
        if (!Number.isFinite(retryMilliseconds) || retryMilliseconds <= 0) {
            throw new RangeError(
                "Rendezvous retry duration must be finite and positive",
            );
        }
        this.messageHandler = (
            peer: AgentCommunicationPeer,
            message: AgentCommunicationMessage,
        ): Promise<void> => this.handleMessage(peer, message);
        this.peerStatusHandler = (
            _peer: AgentCommunicationPeer,
            status: AGENT_COMMUNICATION_PEER_STATUS,
        ): void => {
            if (status === AGENT_COMMUNICATION_PEER_STATUS.CONNECTED) {
                void this.retryPendingMessages();
            }
        };
    }

    start(): void {
        if (this.started) {
            throw new Error("The rendezvous coordinator is already started");
        }
        this.started = true;
        this.channel.subscribe(this.messageHandler);
        this.channel.subscribePeerStatus(this.peerStatusHandler);
        this.retryTimer = setInterval(
            (): void => void this.retryPendingMessages(),
            this.retryMilliseconds,
        );
    }

    stop(): void {
        if (this.retryTimer) {
            clearInterval(this.retryTimer);
            this.retryTimer = undefined;
        }
        this.channel.unsubscribe(this.messageHandler);
        this.channel.unsubscribePeerStatus(this.peerStatusHandler);
        this.started = false;
    }

    propose(plan: RendezvousCoordinationPlan): void {
        if (this.localRole !== AGENT_ROLE.LLM) {
            throw new Error("Only the LLM agent can propose a rendezvous");
        }
        if (this.records.has(plan.rendezvousId)) {
            throw new Error(`Duplicate rendezvous ${plan.rendezvousId}`);
        }
        const assignmentMessage =
            AgentCommunicationMessageFactory.rendezvousAssignment(
                plan.rendezvousId,
                plan.reward,
                plan.llmAgentTarget,
                plan.bdiAgentTarget,
            );
        this.records.set(plan.rendezvousId, {
            rendezvousId: plan.rendezvousId,
            reward: plan.reward,
            localTarget: plan.llmAgentTarget,
            peerTarget: plan.bdiAgentTarget,
            localObjective: undefined,
            assignmentMessage,
            formationProposalMessage: undefined,
            peerObjective: undefined,
            receivedFormationProposalMessage: undefined,
            formationAcceptanceMessage: undefined,
            requiresExternalRelease: false,
            state: RENDEZVOUS_COORDINATION_STATE.PROPOSING,
            peerArrived: false,
            arrivalAcknowledged: false,
            arrivalMessage: undefined,
            releaseMessage: undefined,
            commitmentWaiters: new Set<() => void>(),
            completionWaiters: new Set<() => void>(),
        });
        void this.channel.send(assignmentMessage);
    }

    /** Registers an abstract formation without contacting the peer yet. */
    considerGridFormation(plan: GridFormationCoordinationPlan): void {
        if (this.localRole !== AGENT_ROLE.LLM) {
            throw new Error("Only the LLM agent can introduce a grid formation");
        }
        if (this.records.has(plan.rendezvousId)) {
            throw new Error(`Duplicate rendezvous ${plan.rendezvousId}`);
        }
        this.records.set(plan.rendezvousId, {
            rendezvousId: plan.rendezvousId,
            reward: plan.reward,
            localTarget: undefined,
            peerTarget: undefined,
            localObjective: plan.llmAgentObjective,
            assignmentMessage: undefined,
            formationProposalMessage: undefined,
            peerObjective: plan.bdiAgentObjective,
            receivedFormationProposalMessage: undefined,
            formationAcceptanceMessage: undefined,
            requiresExternalRelease: true,
            state: RENDEZVOUS_COORDINATION_STATE.CONSIDERING,
            peerArrived: false,
            arrivalAcknowledged: false,
            arrivalMessage: undefined,
            releaseMessage: undefined,
            commitmentWaiters: new Set<() => void>(),
            completionWaiters: new Set<() => void>(),
        });
    }

    /** Freezes the currently selected target and starts or accepts negotiation. */
    commitSelectedGridFormation(
        effectId: string,
        target: Position,
    ): boolean {
        const record = [...this.records.values()].find(
            (candidate: RendezvousRecord): boolean =>
                candidate.state === RENDEZVOUS_COORDINATION_STATE.CONSIDERING
                && this.gridFormationEffectId(candidate) === effectId,
        );
        if (
            !record
            || !record.localObjective?.matches(target.x, target.y)
            || record.peerTarget?.isEqual(target)
        ) {
            return false;
        }

        if (this.localRole === AGENT_ROLE.LLM) {
            const peerObjective = record.peerObjective;
            if (!peerObjective) {
                return false;
            }
            record.localTarget = new Position(target.x, target.y);
            record.formationProposalMessage =
                AgentCommunicationMessageFactory.gridFormationProposal(
                    record.rendezvousId,
                    record.reward,
                    record.localTarget,
                    record.localObjective.describe(),
                    peerObjective.describe(),
                );
            record.state = RENDEZVOUS_COORDINATION_STATE.PROPOSING;
            void this.channel.send(record.formationProposalMessage);
        } else {
            const proposal = record.receivedFormationProposalMessage;
            if (!proposal) {
                return false;
            }
            record.localTarget = new Position(target.x, target.y);
            record.formationAcceptanceMessage =
                AgentCommunicationMessageFactory.gridFormationAcceptance(
                    record.rendezvousId,
                    proposal.messageId,
                    record.localTarget,
                );
            record.state = RENDEZVOUS_COORDINATION_STATE.COMMITTED;
            void this.channel.send(record.formationAcceptanceMessage);
        }
        this.publishStateChange();
        return true;
    }

    /** Blocks a selected proposer until its peer accepts the frozen target. */
    async waitForGridFormationCommit(): Promise<void> {
        const proposingRecords = [...this.records.values()].filter(
            (record: RendezvousRecord): boolean =>
                record.state === RENDEZVOUS_COORDINATION_STATE.PROPOSING
                && record.localObjective !== undefined,
        );
        await Promise.all(proposingRecords.map(
            (record: RendezvousRecord): Promise<void> =>
                new Promise<void>((resolve: () => void): void => {
                    if (
                        record.state
                            !== RENDEZVOUS_COORDINATION_STATE.PROPOSING
                    ) {
                        resolve();
                        return;
                    }
                    record.commitmentWaiters.add(resolve);
                }),
        ));
    }

    isGridFormationEffect(effectId: string): boolean {
        return [...this.records.values()].some(
            (record: RendezvousRecord): boolean =>
                record.localObjective !== undefined
                && this.gridFormationEffectId(record) === effectId,
        );
    }

    observePosition(position: Position): void {
        this.latestPosition = new Position(position.x, position.y);
        for (const record of this.records.values()) {
            if (
                record.state !== RENDEZVOUS_COORDINATION_STATE.COMMITTED
                || !record.localTarget
                || !position.isEqual(record.localTarget)
            ) {
                continue;
            }
            record.arrivalMessage =
                AgentCommunicationMessageFactory.rendezvousArrived(
                    this.localRole,
                    record.rendezvousId,
                    record.localTarget,
                );
            record.arrivalAcknowledged = false;
            if (record.peerArrived) {
                this.completeOrWaitForRelease(record);
            } else {
                record.state =
                    RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER;
                this.publishStateChange();
            }
            void this.channel.send(record.arrivalMessage);
        }
    }

    activeScoreEffects(): readonly CellScoreEffect[] {
        const effects: CellScoreEffect[] = [];
        for (const record of this.records.values()) {
            let target: Position | undefined;
            if (record.state === RENDEZVOUS_COORDINATION_STATE.COMMITTED) {
                target = record.localTarget;
            } else if (
                record.state === RENDEZVOUS_COORDINATION_STATE.CONSIDERING
                && record.localObjective
                && this.resolveGridPosition
                && this.latestPosition
            ) {
                target = this.resolveGridPosition(
                    record.localObjective,
                    this.latestPosition,
                    record.peerTarget ? [record.peerTarget] : [],
                );
            }
            if (!target) {
                continue;
            }
            effects.push(new CellScoreEffect(
                record.localObjective
                    ? this.gridFormationEffectId(record)
                    : `rendezvous:${record.rendezvousId}:${this.localRole}`,
                target,
                record.reward,
                SCORE_EFFECT_LIFETIME.ONE_SHOT,
                record.localObjective !== undefined,
            ));
        }
        return effects;
    }

    isWaitingForPeer(): boolean {
        return [...this.records.values()].some(
            (record: RendezvousRecord): boolean =>
                record.state
                    === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER
                || record.state
                    === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_RELEASE,
        );
    }

    async waitForPeer(): Promise<void> {
        const waitingRecords = [...this.records.values()].filter(
            (record: RendezvousRecord): boolean =>
                record.state
                    === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER
                || record.state
                    === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_RELEASE,
        );
        await Promise.all(
            waitingRecords.map(
                (record: RendezvousRecord): Promise<void> =>
                    new Promise<void>((resolve: () => void): void => {
                        if (
                            record.state
                                === RENDEZVOUS_COORDINATION_STATE.COMPLETED
                        ) {
                            resolve();
                            return;
                        }
                        record.completionWaiters.add(resolve);
                    }),
            ),
        );
    }

    /** Sends a reliable green light for every arrived grid formation. */
    releaseWaitingGridFormations(): boolean {
        if (this.localRole !== AGENT_ROLE.LLM) {
            return false;
        }
        let released = false;
        for (const record of this.records.values()) {
            if (
                !record.requiresExternalRelease
                || (
                    record.state
                        !== RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER
                    && record.state
                        !== RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_RELEASE
                )
                || record.releaseMessage
            ) {
                continue;
            }
            record.releaseMessage =
                AgentCommunicationMessageFactory.gridFormationRelease(
                    record.rendezvousId,
                );
            void this.channel.send(record.releaseMessage);
            released = true;
        }
        return released;
    }

    consumeCompletedRendezvousIds(): readonly string[] {
        return this.completedRendezvousIds.splice(
            0,
            this.completedRendezvousIds.length,
        );
    }

    snapshots(): readonly RendezvousCoordinationSnapshot[] {
        return [...this.records.values()].map(
            (record: RendezvousRecord): RendezvousCoordinationSnapshot => ({
                rendezvousId: record.rendezvousId,
                localTarget: record.localTarget,
                peerTarget: record.peerTarget,
                reward: record.reward,
                state: record.state,
                peerArrived: record.peerArrived,
                arrivalAcknowledged: record.arrivalAcknowledged,
            }),
        );
    }

    subscribeStateChanges(handler: RendezvousStateChangeHandler): void {
        this.stateChangeHandlers.add(handler);
    }

    private async handleMessage(
        _peer: AgentCommunicationPeer,
        message: AgentCommunicationMessage,
    ): Promise<void> {
        if (message.role === this.localRole) {
            return;
        }
        switch (message.type) {
            case PEER_MESSAGE_TYPE.RENDEZVOUS_ASSIGNMENT:
                await this.handleAssignment(message);
                return;
            case PEER_MESSAGE_TYPE.RENDEZVOUS_ACKNOWLEDGEMENT:
                this.handleAcknowledgement(message);
                return;
            case PEER_MESSAGE_TYPE.GRID_FORMATION_PROPOSAL:
                await this.handleGridFormationProposal(message);
                return;
            case PEER_MESSAGE_TYPE.GRID_FORMATION_ACCEPTANCE:
                this.handleGridFormationAcceptance(message);
                return;
            case PEER_MESSAGE_TYPE.GRID_FORMATION_RELEASE:
                await this.handleGridFormationRelease(message);
                return;
            case PEER_MESSAGE_TYPE.GRID_FORMATION_RELEASE_ACKNOWLEDGEMENT:
                this.handleGridFormationReleaseAcknowledgement(message);
                return;
            case PEER_MESSAGE_TYPE.RENDEZVOUS_ARRIVED:
                await this.handlePeerArrival(message);
                return;
            case PEER_MESSAGE_TYPE.RENDEZVOUS_ARRIVAL_ACKNOWLEDGEMENT:
                this.handleArrivalAcknowledgement(message);
                return;
            default:
                return;
        }
    }

    private async handleAssignment(
        message: RendezvousAssignmentMessage,
    ): Promise<void> {
        if (this.localRole !== AGENT_ROLE.BDI) {
            return;
        }
        let record = this.records.get(message.rendezvousId);
        if (!record) {
            record = {
                rendezvousId: message.rendezvousId,
                reward: message.reward,
                localTarget: new Position(
                    message.bdiAgentTarget.x,
                    message.bdiAgentTarget.y,
                ),
                peerTarget: new Position(
                    message.llmAgentTarget.x,
                    message.llmAgentTarget.y,
                ),
                localObjective: undefined,
                assignmentMessage: undefined,
                formationProposalMessage: undefined,
                peerObjective: undefined,
                receivedFormationProposalMessage: undefined,
                formationAcceptanceMessage: undefined,
                requiresExternalRelease: false,
                state: RENDEZVOUS_COORDINATION_STATE.COMMITTED,
                peerArrived: false,
                arrivalAcknowledged: false,
                arrivalMessage: undefined,
                releaseMessage: undefined,
                commitmentWaiters: new Set<() => void>(),
                completionWaiters: new Set<() => void>(),
            };
            this.records.set(message.rendezvousId, record);
            this.publishStateChange();
        }
        await this.channel.send(
            AgentCommunicationMessageFactory.rendezvousAcknowledgement(
                message.rendezvousId,
                message.messageId,
            ),
        );
        if (record.arrivalMessage && !record.arrivalAcknowledged) {
            await this.channel.send(record.arrivalMessage);
        }
    }

    private handleAcknowledgement(
        message: AgentCommunicationMessage & {
            readonly type: PEER_MESSAGE_TYPE.RENDEZVOUS_ACKNOWLEDGEMENT;
        },
    ): void {
        if (this.localRole !== AGENT_ROLE.LLM) {
            return;
        }
        const record = this.records.get(message.rendezvousId);
        if (
            !record
            || record.state !== RENDEZVOUS_COORDINATION_STATE.PROPOSING
            || record.assignmentMessage?.messageId
                !== message.acknowledgedMessageId
        ) {
            return;
        }
        record.state = RENDEZVOUS_COORDINATION_STATE.COMMITTED;
        this.publishStateChange();
    }

    private async handlePeerArrival(
        message: RendezvousArrivedMessage,
    ): Promise<void> {
        const record = this.records.get(message.rendezvousId);
        if (
            !record
            || !record.peerTarget
            || record.peerTarget.x !== message.position.x
            || record.peerTarget.y !== message.position.y
        ) {
            return;
        }
        await this.channel.send(
            AgentCommunicationMessageFactory
                .rendezvousArrivalAcknowledgement(
                    this.localRole,
                    message.rendezvousId,
                    message.messageId,
                ),
        );
        record.peerArrived = true;
        if (
            record.state
                === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER
        ) {
            this.completeOrWaitForRelease(record);
            return;
        }
    }

    private handleArrivalAcknowledgement(
        message: RendezvousArrivalAcknowledgementMessage,
    ): void {
        const record = this.records.get(message.rendezvousId);
        if (
            !record
            || record.arrivalMessage?.messageId
                !== message.acknowledgedMessageId
        ) {
            return;
        }
        record.arrivalAcknowledged = true;
    }

    private complete(record: RendezvousRecord): void {
        record.state = RENDEZVOUS_COORDINATION_STATE.COMPLETED;
        this.completedRendezvousIds.push(record.rendezvousId);
        for (const resolve of record.completionWaiters) {
            resolve();
        }
        record.completionWaiters.clear();
        this.publishStateChange();
    }

    private async retryPendingMessages(): Promise<void> {
        for (const record of this.records.values()) {
            if (
                record.state === RENDEZVOUS_COORDINATION_STATE.PROPOSING
                && record.assignmentMessage
            ) {
                await this.channel.send(record.assignmentMessage);
            }
            if (
                record.state === RENDEZVOUS_COORDINATION_STATE.PROPOSING
                && record.formationProposalMessage
            ) {
                await this.channel.send(record.formationProposalMessage);
            }
            if (
                (
                    record.state
                        === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER
                    || record.state
                        === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_RELEASE
                )
                && record.releaseMessage
            ) {
                await this.channel.send(record.releaseMessage);
            }
            if (
                (
                    record.state
                        === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER
                    || record.state
                        === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_RELEASE
                    || record.state
                        === RENDEZVOUS_COORDINATION_STATE.COMPLETED
                )
                && record.arrivalMessage
                && !record.arrivalAcknowledged
            ) {
                await this.channel.send(record.arrivalMessage);
            }
        }
    }

    private publishStateChange(): void {
        for (const handler of this.stateChangeHandlers) {
            handler();
        }
    }

    private async handleGridFormationProposal(
        message: GridFormationProposalMessage,
    ): Promise<void> {
        if (this.localRole !== AGENT_ROLE.BDI) {
            return;
        }
        let record = this.records.get(message.rendezvousId);
        if (!record) {
            const bdiObjective = GridPositionObjective.parse(
                message.bdiAgentObjective,
            );
            const llmObjective = GridPositionObjective.parse(
                message.llmAgentObjective,
            );
            if (
                !bdiObjective
                || !llmObjective
                || !llmObjective.matches(
                    message.llmAgentTarget.x,
                    message.llmAgentTarget.y,
                )
            ) {
                return;
            }
            record = {
                rendezvousId: message.rendezvousId,
                reward: message.reward,
                localTarget: undefined,
                peerTarget: new Position(
                    message.llmAgentTarget.x,
                    message.llmAgentTarget.y,
                ),
                localObjective: bdiObjective,
                assignmentMessage: undefined,
                formationProposalMessage: undefined,
                peerObjective: undefined,
                receivedFormationProposalMessage: message,
                formationAcceptanceMessage: undefined,
                requiresExternalRelease: true,
                state: RENDEZVOUS_COORDINATION_STATE.CONSIDERING,
                peerArrived: false,
                arrivalAcknowledged: false,
                arrivalMessage: undefined,
                releaseMessage: undefined,
                commitmentWaiters: new Set<() => void>(),
                completionWaiters: new Set<() => void>(),
            };
            this.records.set(message.rendezvousId, record);
            this.publishStateChange();
        }
        if (record.formationAcceptanceMessage) {
            await this.channel.send(record.formationAcceptanceMessage);
        }
    }

    private handleGridFormationAcceptance(
        message: GridFormationAcceptanceMessage,
    ): void {
        if (this.localRole !== AGENT_ROLE.LLM) {
            return;
        }
        const record = this.records.get(message.rendezvousId);
        if (
            !record
            || record.state !== RENDEZVOUS_COORDINATION_STATE.PROPOSING
            || record.formationProposalMessage?.messageId
                !== message.acknowledgedMessageId
            || !record.peerObjective?.matches(
                message.bdiAgentTarget.x,
                message.bdiAgentTarget.y,
            )
            || !record.localTarget
            || record.localTarget.x === message.bdiAgentTarget.x
                && record.localTarget.y === message.bdiAgentTarget.y
        ) {
            return;
        }
        record.peerTarget = new Position(
            message.bdiAgentTarget.x,
            message.bdiAgentTarget.y,
        );
        record.state = RENDEZVOUS_COORDINATION_STATE.COMMITTED;
        for (const resolve of record.commitmentWaiters) {
            resolve();
        }
        record.commitmentWaiters.clear();
        this.publishStateChange();
    }

    private async handleGridFormationRelease(
        message: GridFormationReleaseMessage,
    ): Promise<void> {
        if (this.localRole !== AGENT_ROLE.BDI) {
            return;
        }
        const record = this.records.get(message.rendezvousId);
        if (
            !record
            || !record.requiresExternalRelease
            || record.state
                !== RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_RELEASE
                && record.state
                    !== RENDEZVOUS_COORDINATION_STATE.COMPLETED
        ) {
            return;
        }
        await this.channel.send(
            AgentCommunicationMessageFactory
                .gridFormationReleaseAcknowledgement(
                    message.rendezvousId,
                    message.messageId,
                ),
        );
        if (record.state !== RENDEZVOUS_COORDINATION_STATE.COMPLETED) {
            this.complete(record);
        }
    }

    private handleGridFormationReleaseAcknowledgement(
        message: GridFormationReleaseAcknowledgementMessage,
    ): void {
        if (this.localRole !== AGENT_ROLE.LLM) {
            return;
        }
        const record = this.records.get(message.rendezvousId);
        if (
            !record
            || record.state
                !== RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_RELEASE
            || record.releaseMessage?.messageId
                !== message.acknowledgedMessageId
        ) {
            return;
        }
        this.complete(record);
    }

    private completeOrWaitForRelease(record: RendezvousRecord): void {
        if (record.requiresExternalRelease) {
            record.state = RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_RELEASE;
            this.publishStateChange();
            return;
        }
        this.complete(record);
    }

    private gridFormationEffectId(record: RendezvousRecord): string {
        return `grid-formation:${record.rendezvousId}:${this.localRole}`;
    }
}
