import {
    AGENT_COMMUNICATION_PEER_STATUS,
    AGENT_ROLE,
    BaseAgentCommunicationChannel,
    type AgentCommunicationMessage,
    type AgentCommunicationMessageHandler,
    AgentCommunicationMessageFactory,
    type AgentCommunicationPeer,
    type AgentCommunicationPeerStatusHandler,
    PEER_MESSAGE_TYPE,
    type RendezvousArrivedMessage,
    type RendezvousAssignmentMessage,
} from "../../../communication/index.js";
import { SCORE_EFFECT_LIFETIME } from "../../../_score-effect-lifetime.js";
import { CellScoreEffect } from "../../../utils/_cell-score-effects.js";
import { Position } from "../../../utils/position.js";

/** State of one local participant in the rendezvous protocol. */
export enum RENDEZVOUS_COORDINATION_STATE {
    PROPOSING = "proposing",
    COMMITTED = "committed",
    WAITING_FOR_PEER = "waiting-for-peer",
    COMPLETED = "completed",
}

/** Transport-neutral rendezvous generated by the LLM mission planner. */
export interface RendezvousCoordinationPlan {
    readonly rendezvousId: string;
    readonly reward: number;
    readonly llmAgentTarget: Position;
    readonly bdiAgentTarget: Position;
}

/** Read-only coordinator state useful to tests and observers. */
export interface RendezvousCoordinationSnapshot {
    readonly rendezvousId: string;
    readonly localTarget: Position;
    readonly peerTarget: Position;
    readonly reward: number;
    readonly state: RENDEZVOUS_COORDINATION_STATE;
    readonly peerArrived: boolean;
}

interface RendezvousRecord {
    readonly rendezvousId: string;
    readonly reward: number;
    readonly localTarget: Position;
    readonly peerTarget: Position;
    readonly assignmentMessage: RendezvousAssignmentMessage | undefined;
    state: RENDEZVOUS_COORDINATION_STATE;
    peerArrived: boolean;
    arrivalMessage: RendezvousArrivedMessage | undefined;
    completionWaiters: Set<() => void>;
}

export type RendezvousStateChangeHandler = () => void;

/** Contract connecting rendezvous communication to an autonomous planner. */
export abstract class BaseRendezvousCoordinator {
    abstract start(): void;
    abstract stop(): void;
    abstract propose(plan: RendezvousCoordinationPlan): void;
    abstract observePosition(position: Position): void;
    abstract activeScoreEffects(): readonly CellScoreEffect[];
    abstract isWaitingForPeer(): boolean;
    abstract waitForPeer(): Promise<void>;
    abstract consumeCompletedRendezvousIds(): readonly string[];
    abstract snapshots(): readonly RendezvousCoordinationSnapshot[];
    abstract subscribeStateChanges(handler: RendezvousStateChangeHandler): void;
}

/** Reliable two-peer rendezvous state machine over the shared agent channel. */
export class PeerRendezvousCoordinator extends BaseRendezvousCoordinator {
    private readonly records: Map<string, RendezvousRecord> =
        new Map<string, RendezvousRecord>();
    private readonly stateChangeHandlers: Set<RendezvousStateChangeHandler> =
        new Set<RendezvousStateChangeHandler>();
    private readonly completedRendezvousIds: string[] = [];
    private readonly messageHandler: AgentCommunicationMessageHandler;
    private readonly peerStatusHandler: AgentCommunicationPeerStatusHandler;
    private retryTimer: NodeJS.Timeout | undefined;
    private started: boolean = false;

    constructor(
        private readonly channel: BaseAgentCommunicationChannel,
        private readonly localRole: AGENT_ROLE,
        private readonly retryMilliseconds: number = 1_000,
    ) {
        super();
        if (!Number.isFinite(retryMilliseconds) || retryMilliseconds <= 0) {
            throw new RangeError(
                "Rendezvous retry duration must be finite and positive",
            );
        }
        this.messageHandler = (
            peer: AgentCommunicationPeer,
            message: AgentCommunicationMessage,
        ): Promise<void> => this.handleMessage(peer, message);
        this.peerStatusHandler = (
            _peer: AgentCommunicationPeer,
            status: AGENT_COMMUNICATION_PEER_STATUS,
        ): void => {
            if (status === AGENT_COMMUNICATION_PEER_STATUS.CONNECTED) {
                void this.retryPendingMessages();
            }
        };
    }

    start(): void {
        if (this.started) {
            throw new Error("The rendezvous coordinator is already started");
        }
        this.started = true;
        this.channel.subscribe(this.messageHandler);
        this.channel.subscribePeerStatus(this.peerStatusHandler);
        this.retryTimer = setInterval(
            (): void => void this.retryPendingMessages(),
            this.retryMilliseconds,
        );
    }

    stop(): void {
        if (this.retryTimer) {
            clearInterval(this.retryTimer);
            this.retryTimer = undefined;
        }
        this.channel.unsubscribe(this.messageHandler);
        this.channel.unsubscribePeerStatus(this.peerStatusHandler);
        this.started = false;
    }

    propose(plan: RendezvousCoordinationPlan): void {
        if (this.localRole !== AGENT_ROLE.LLM) {
            throw new Error("Only the LLM agent can propose a rendezvous");
        }
        if (this.records.has(plan.rendezvousId)) {
            throw new Error(`Duplicate rendezvous ${plan.rendezvousId}`);
        }
        const assignmentMessage =
            AgentCommunicationMessageFactory.rendezvousAssignment(
                plan.rendezvousId,
                plan.reward,
                plan.llmAgentTarget,
                plan.bdiAgentTarget,
            );
        this.records.set(plan.rendezvousId, {
            rendezvousId: plan.rendezvousId,
            reward: plan.reward,
            localTarget: plan.llmAgentTarget,
            peerTarget: plan.bdiAgentTarget,
            assignmentMessage,
            state: RENDEZVOUS_COORDINATION_STATE.PROPOSING,
            peerArrived: false,
            arrivalMessage: undefined,
            completionWaiters: new Set<() => void>(),
        });
        void this.channel.send(assignmentMessage);
    }

    observePosition(position: Position): void {
        for (const record of this.records.values()) {
            if (
                record.state !== RENDEZVOUS_COORDINATION_STATE.COMMITTED
                || !position.isEqual(record.localTarget)
            ) {
                continue;
            }
            record.arrivalMessage =
                AgentCommunicationMessageFactory.rendezvousArrived(
                    this.localRole,
                    record.rendezvousId,
                    record.localTarget,
                );
            if (record.peerArrived) {
                this.complete(record);
            } else {
                record.state =
                    RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER;
                this.publishStateChange();
            }
            void this.channel.send(record.arrivalMessage);
        }
    }

    activeScoreEffects(): readonly CellScoreEffect[] {
        return [...this.records.values()]
            .filter(
                (record: RendezvousRecord): boolean =>
                    record.state === RENDEZVOUS_COORDINATION_STATE.COMMITTED,
            )
            .map(
                (record: RendezvousRecord): CellScoreEffect =>
                    new CellScoreEffect(
                        `rendezvous:${record.rendezvousId}:${this.localRole}`,
                        record.localTarget,
                        record.reward,
                        SCORE_EFFECT_LIFETIME.ONE_SHOT,
                    ),
            );
    }

    isWaitingForPeer(): boolean {
        return [...this.records.values()].some(
            (record: RendezvousRecord): boolean =>
                record.state
                    === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER,
        );
    }

    async waitForPeer(): Promise<void> {
        const waitingRecords = [...this.records.values()].filter(
            (record: RendezvousRecord): boolean =>
                record.state
                    === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER,
        );
        await Promise.all(
            waitingRecords.map(
                (record: RendezvousRecord): Promise<void> =>
                    new Promise<void>((resolve: () => void): void => {
                        if (
                            record.state
                                === RENDEZVOUS_COORDINATION_STATE.COMPLETED
                        ) {
                            resolve();
                            return;
                        }
                        record.completionWaiters.add(resolve);
                    }),
            ),
        );
    }

    consumeCompletedRendezvousIds(): readonly string[] {
        return this.completedRendezvousIds.splice(
            0,
            this.completedRendezvousIds.length,
        );
    }

    snapshots(): readonly RendezvousCoordinationSnapshot[] {
        return [...this.records.values()].map(
            (record: RendezvousRecord): RendezvousCoordinationSnapshot => ({
                rendezvousId: record.rendezvousId,
                localTarget: record.localTarget,
                peerTarget: record.peerTarget,
                reward: record.reward,
                state: record.state,
                peerArrived: record.peerArrived,
            }),
        );
    }

    subscribeStateChanges(handler: RendezvousStateChangeHandler): void {
        this.stateChangeHandlers.add(handler);
    }

    private async handleMessage(
        _peer: AgentCommunicationPeer,
        message: AgentCommunicationMessage,
    ): Promise<void> {
        if (message.role === this.localRole) {
            return;
        }
        switch (message.type) {
            case PEER_MESSAGE_TYPE.RENDEZVOUS_ASSIGNMENT:
                await this.handleAssignment(message);
                return;
            case PEER_MESSAGE_TYPE.RENDEZVOUS_ACKNOWLEDGEMENT:
                this.handleAcknowledgement(message);
                return;
            case PEER_MESSAGE_TYPE.RENDEZVOUS_ARRIVED:
                await this.handlePeerArrival(message);
                return;
            default:
                return;
        }
    }

    private async handleAssignment(
        message: RendezvousAssignmentMessage,
    ): Promise<void> {
        if (this.localRole !== AGENT_ROLE.BDI) {
            return;
        }
        let record = this.records.get(message.rendezvousId);
        if (!record) {
            record = {
                rendezvousId: message.rendezvousId,
                reward: message.reward,
                localTarget: new Position(
                    message.bdiAgentTarget.x,
                    message.bdiAgentTarget.y,
                ),
                peerTarget: new Position(
                    message.llmAgentTarget.x,
                    message.llmAgentTarget.y,
                ),
                assignmentMessage: undefined,
                state: RENDEZVOUS_COORDINATION_STATE.COMMITTED,
                peerArrived: false,
                arrivalMessage: undefined,
                completionWaiters: new Set<() => void>(),
            };
            this.records.set(message.rendezvousId, record);
            this.publishStateChange();
        }
        await this.channel.send(
            AgentCommunicationMessageFactory.rendezvousAcknowledgement(
                message.rendezvousId,
                message.messageId,
            ),
        );
        if (record.arrivalMessage) {
            await this.channel.send(record.arrivalMessage);
        }
    }

    private handleAcknowledgement(
        message: AgentCommunicationMessage & {
            readonly type: PEER_MESSAGE_TYPE.RENDEZVOUS_ACKNOWLEDGEMENT;
        },
    ): void {
        if (this.localRole !== AGENT_ROLE.LLM) {
            return;
        }
        const record = this.records.get(message.rendezvousId);
        if (
            !record
            || record.state !== RENDEZVOUS_COORDINATION_STATE.PROPOSING
            || record.assignmentMessage?.messageId
                !== message.acknowledgedMessageId
        ) {
            return;
        }
        record.state = RENDEZVOUS_COORDINATION_STATE.COMMITTED;
        this.publishStateChange();
    }

    private async handlePeerArrival(
        message: RendezvousArrivedMessage,
    ): Promise<void> {
        const record = this.records.get(message.rendezvousId);
        if (
            !record
            || record.peerTarget.x !== message.position.x
            || record.peerTarget.y !== message.position.y
        ) {
            return;
        }
        record.peerArrived = true;
        if (
            record.state
                === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER
        ) {
            this.complete(record);
            return;
        }
        if (
            record.state === RENDEZVOUS_COORDINATION_STATE.COMPLETED
            && record.arrivalMessage
        ) {
            await this.channel.send(record.arrivalMessage);
        }
    }

    private complete(record: RendezvousRecord): void {
        record.state = RENDEZVOUS_COORDINATION_STATE.COMPLETED;
        this.completedRendezvousIds.push(record.rendezvousId);
        for (const resolve of record.completionWaiters) {
            resolve();
        }
        record.completionWaiters.clear();
        this.publishStateChange();
    }

    private async retryPendingMessages(): Promise<void> {
        for (const record of this.records.values()) {
            if (
                record.state === RENDEZVOUS_COORDINATION_STATE.PROPOSING
                && record.assignmentMessage
            ) {
                await this.channel.send(record.assignmentMessage);
            }
            if (
                record.state
                    === RENDEZVOUS_COORDINATION_STATE.WAITING_FOR_PEER
                && record.arrivalMessage
            ) {
                await this.channel.send(record.arrivalMessage);
            }
        }
    }

    private publishStateChange(): void {
        for (const handler of this.stateChangeHandlers) {
            handler();
        }
    }
}
